servers:
  - port: 8080
    server_name: example.com
    error_pages:
      404: ./web/errors/error404.html
      500: ./web/errors/error500.html
    client_max_body_size: 1048576
    routes:
      - url: /
        methods: [GET]
        root: ./web/www/example1
      - url: /form_submit
        methods: [POST]
        root: ./web/www/example1/form_submit
      - url: /put_test
        methods: [PUT]
        upload_dir: ./web/uploads/example1/put_test
      - url: /cgi-bin/script
        methods: [POST, GET]
        cgi_path: ./cgi_tester_py
      - url: /post_body
        methods: [POST]
        max_body: 100
      - url: /directory
        methods: [GET, POST]
        alias: ./YoupiBanane
        index: youpi.bad_extension
        autoIndex: off
      - url: .bla
        methods: [POST, GET]
        cgi_path: ./cgi_tester
  - port: 8081
    server_name: example.com
    error_pages:
      404: ./web/errors/error404.html
      500: ./web/errors/error500.html
    client_max_body_size: 1048576
    routes:
      - url: /
        methods: [GET]
        root: ./web/www/example2
      - url: /form_submit
        methods: [POST]
        root: ./web/www/example2/form_submit
      - url: /put_test
        methods: [PUT]
        upload_dir: ./web/uploads/example2/put_test
      - url: /cgi-bin/script
        methods: [POST, GET]
        cgi_path: ./cgi_tester_py
      - url: /post_body
        methods: [POST]
        max_body: 100
      - url: /directory
        methods: [GET, POST]
        alias: ./YoupiBanane
        index: youpi.bad_extension
        autoIndex: on
      - url: .bla
        methods: [POST, GET]
        cgi_path: ./cgi_tester